// Generated by the TMDB workflow from series-input.js.
window.WLW_CATALOG = {
  "USA": {
    "code": "USA",
    "title": "USA",
    "type": "country",
    "movies": [
      {
        "title": "A League of Their Own",
        "year": 2022
      },
      {
        "title": "Adventure Time",
        "year": 2010
      },
      {
        "title": "Agatha All Along",
        "year": 2024
      },
      {
        "title": "Arcane",
        "year": 2021
      },
      {
        "title": "Atypical",
        "year": 2017
      },
      {
        "title": "The Beast in Me",
        "year": 2025
      },
      {
        "title": "Bridgerton",
        "year": 2020
      },
      {
        "title": "Buffy the Vampire Slayer",
        "year": 1997
      },
      {
        "title": "Cruel Intentions",
        "year": 2024
      },
      {
        "title": "DC’s Legends of Tomorrow",
        "year": 2016
      },
      {
        "title": "Dickinson",
        "year": 2019
      },
      {
        "title": "The Dynasty: UConn Huskies",
        "year": 2026
      },
      {
        "title": "Elle",
        "year": 2026
      },
      {
        "title": "Euphoria",
        "year": 2019
      },
      {
        "title": "First Kill",
        "year": 2022
      },
      {
        "title": "The Good Fight",
        "year": 2017
      },
      {
        "title": "Grey’s Anatomy",
        "year": 2005
      },
      {
        "title": "Hacks",
        "year": 2021
      },
      {
        "title": "Hal & Harper",
        "year": 2025
      },
      {
        "title": "Harley Quinn",
        "year": 2019
      },
      {
        "title": "The Haunting of Bly Manor",
        "year": 2020
      },
      {
        "title": "The Hunting Wives",
        "year": 2025
      },
      {
        "title": "Interview with the Vampire",
        "year": 2022
      },
      {
        "title": "Jessica Jones",
        "year": 2015
      },
      {
        "title": "The L Word",
        "year": 2004
      },
      {
        "title": "The Last of Us",
        "year": 2023
      },
      {
        "title": "The Legend of Korra",
        "year": 2012
      },
      {
        "title": "Leopard Skin",
        "year": 2022
      },
      {
        "title": "Long Story Short",
        "year": 2025
      },
      {
        "title": "Monster: The Lizzie Borden Story",
        "year": 2026
      },
      {
        "title": "The Owl House",
        "year": 2020
      },
      {
        "title": "Paper Girls",
        "year": 2022
      },
      {
        "title": "Person of Interest",
        "year": 2011
      },
      {
        "title": "Pluribus",
        "year": 2025
      },
      {
        "title": "Queer for Fear: The History of Queer Horror",
        "year": 2022
      },
      {
        "title": "Rizzoli & Isles",
        "year": 2010
      },
      {
        "title": "Sharp Objects",
        "year": 2018
      },
      {
        "title": "She-Hulk: Attorney at Law",
        "year": 2022
      },
      {
        "title": "South of Nowhere",
        "year": 2005
      },
      {
        "title": "Special Ops: Lioness",
        "year": 2023
      },
      {
        "title": "Station 19",
        "year": 2018
      },
      {
        "title": "Sterling Point",
        "year": 2026
      },
      {
        "title": "Supergirl",
        "year": 2015
      },
      {
        "title": "Swimming with Sharks",
        "year": 2022
      },
      {
        "title": "Teenage Bounty Hunters",
        "year": 2020
      },
      {
        "title": "Warehouse 13",
        "year": 2009
      },
      {
        "title": "Wednesday",
        "year": 2022
      },
      {
        "title": "The Wilds",
        "year": 2020
      },
      {
        "title": "Yellowjackets",
        "year": 2021
      }
    ]
  },
  "NED": {
    "code": "NED",
    "title": "NED",
    "type": "country",
    "movies": [
      {
        "title": "ANNE+",
        "year": 2018
      }
    ]
  },
  "ITA": {
    "code": "ITA",
    "title": "ITA",
    "type": "country",
    "movies": [
      {
        "title": "The Art of Joy",
        "year": 2024
      }
    ]
  },
  "GER": {
    "code": "GER",
    "title": "GER",
    "type": "country",
    "movies": [
      {
        "title": "Babylon Berlin",
        "year": 2017
      },
      {
        "title": "Call My Agent Berlin",
        "year": 2025
      },
      {
        "title": "Eldorado KaDeWe",
        "year": 2021
      },
      {
        "title": "Loving Her",
        "year": 2021
      },
      {
        "title": "WIR",
        "year": 2021
      }
    ]
  },
  "AUS": {
    "code": "AUS",
    "title": "AUS",
    "type": "country",
    "movies": [
      {
        "title": "Bad Behaviour",
        "year": 2023
      },
      {
        "title": "Deadloch",
        "year": 2023
      },
      {
        "title": "Triple Oh!",
        "year": 2024
      },
      {
        "title": "Wentworth",
        "year": 2013
      }
    ]
  },
  "UK": {
    "code": "UK",
    "title": "UK",
    "type": "country",
    "movies": [
      {
        "title": "Black Mirror",
        "year": 2011
      },
      {
        "title": "The Buccaneers",
        "year": 2023
      },
      {
        "title": "The Confessions of Frannie Langton",
        "year": 2022
      },
      {
        "title": "The Crow Girl",
        "year": 2025
      },
      {
        "title": "Feel Good",
        "year": 2020
      },
      {
        "title": "Fingersmith",
        "year": 2005
      },
      {
        "title": "Gentleman Jack",
        "year": 2019
      },
      {
        "title": "The Jetty",
        "year": 2024
      },
      {
        "title": "Killing Eve",
        "year": 2018
      },
      {
        "title": "Lip Service",
        "year": 2010
      },
      {
        "title": "Portrait of a Marriage",
        "year": 1990
      },
      {
        "title": "This Way Up",
        "year": 2019
      },
      {
        "title": "Vigil",
        "year": 2021
      }
    ]
  },
  "POR": {
    "code": "POR",
    "title": "POR",
    "type": "country",
    "movies": [
      {
        "title": "Blue Lisbon",
        "year": 2019
      }
    ]
  },
  "NZL": {
    "code": "NZL",
    "title": "NZL",
    "type": "country",
    "movies": [
      {
        "title": "Bust Up",
        "year": 2026
      }
    ]
  },
  "FRA": {
    "code": "FRA",
    "title": "FRA",
    "type": "country",
    "movies": [
      {
        "title": "Dix pour cent",
        "year": 2015
      },
      {
        "title": "Piste noire",
        "year": 2023
      }
    ]
  },
  "CAN": {
    "code": "CAN",
    "title": "CAN",
    "type": "country",
    "movies": [
      {
        "title": "Gay Mean Girls",
        "year": 2015
      },
      {
        "title": "Orphan Black",
        "year": 2013
      },
      {
        "title": "Wynonna Earp",
        "year": 2016
      }
    ]
  },
  "SWE": {
    "code": "SWE",
    "title": "SWE",
    "type": "country",
    "movies": [
      {
        "title": "LIGGA",
        "year": 2021
      },
      {
        "title": "Sjukt oklar",
        "year": 2018
      }
    ]
  },
  "MEX": {
    "code": "MEX",
    "title": "MEX",
    "type": "country",
    "movies": [
      {
        "title": "Señorita 89",
        "year": 2022
      }
    ]
  },
  "JPN": {
    "code": "JPN",
    "title": "JPN",
    "type": "country",
    "movies": [
      {
        "title": "She Loves to Cook, and She Loves to Eat",
        "year": 2022
      }
    ]
  },
  "ESP": {
    "code": "ESP",
    "title": "ESP",
    "type": "country",
    "movies": [
      {
        "title": "Veneno",
        "year": 2020
      }
    ]
  }
};
