// Generated by the TMDB workflow from series-input.js.
window.WLW_OTHERS = [
  {
    "title": "2 Broke Girls",
    "year": 2011
  },
  {
    "title": "Adolescence",
    "year": 2025
  },
  {
    "title": "Better Call Saul",
    "year": 2015
  },
  {
    "title": "Breaking Bad",
    "year": 2008
  },
  {
    "title": "The Capture",
    "year": 2019
  },
  {
    "title": "The Diplomat",
    "year": 2023
  },
  {
    "title": "The English",
    "year": 2022
  },
  {
    "title": "Fisk",
    "year": 2021
  },
  {
    "title": "Maximum Pleasure Guaranteed",
    "year": 2026
  },
  {
    "title": "Modern Family",
    "year": 2009
  },
  {
    "title": "PEN15",
    "year": 2019
  },
  {
    "title": "Rick and Morty",
    "year": 2013
  },
  {
    "title": "Severance",
    "year": 2022
  },
  {
    "title": "Slow Horses",
    "year": 2022
  },
  {
    "title": "The Studio",
    "year": 2025
  },
  {
    "title": "Succession",
    "year": 2018
  },
  {
    "title": "Ted Lasso",
    "year": 2020
  },
  {
    "title": "Twin Peaks",
    "year": 1990
  },
  {
    "title": "Veep",
    "year": 2012
  },
  {
    "title": "The White Lotus",
    "year": 2021
  },
  {
    "title": "Yes, Prime Minister",
    "year": 1986
  }
];
