// Add new series here. Only title, first-air year and others are required.
// others: false = WLW catalogue; true = non-WLW series shown only under Others.
window.WLW_SERIES_INPUT = [
  {"title":"2 Broke Girls","year":2011,"others":true},
  {"title":"A League of Their Own","year":2022,"others":false},
  {"title":"Adolescence","year":2025,"others":true},
  {"title":"Adventure Time","year":2010,"others":false},
  {"title":"Agatha All Along","year":2024,"others":false},
  {"title":"Andor","year":2022,"others":false},
  {"title":"ANNE+","year":2018,"others":false},
  {"title":"Arcane","year":2021,"others":false},
  {"title":"The Art of Joy","year":2024,"others":false},
  {"title":"Atypical","year":2017,"others":false},
  {"title":"Babylon Berlin","year":2017,"others":false},
  {"title":"Bad Behaviour","year":2023,"others":false},
  {"title":"The Beast in Me","year":2025,"others":false},
  {"title":"Better Call Saul","year":2015,"others":true},
  {"title":"Black Mirror","year":2011,"others":false},
  {"title":"Blue Lisbon","year":2019,"others":false},
  {"title":"Breaking Bad","year":2008,"others":true},
  {"title":"Bridgerton","year":2020,"others":false},
  {"title":"The Buccaneers","year":2023,"others":false},
  {"title":"Buffy the Vampire Slayer","year":1997,"others":false},
  {"title":"Bust Up","year":2026,"others":false},
  {"title":"Call My Agent Berlin","year":2025,"others":false},
  {"title":"The Capture","year":2019,"others":true},
  {"title":"The Confessions of Frannie Langton","year":2022,"others":false},
  {"title":"The Crow Girl","year":2025,"others":false},
  {"title":"Cruel Intentions","year":2024,"others":false},
  {"title":"Dark","year":2017,"others":false},
  {"title":"DC’s Legends of Tomorrow","year":2016,"others":false},
  {"title":"Deadloch","year":2023,"others":false},
  {"title":"Dickinson","year":2019,"others":false},
  {"title":"The Diplomat","year":2023,"others":true},
  {"title":"Dix pour cent","year":2015,"others":false},
  {"title":"The Dynasty: UConn Huskies","year":2026,"others":false},
  {"title":"Eldorado KaDeWe","year":2021,"others":false},
  {"title":"Elle","year":2026,"others":false},
  {"title":"The English","year":2022,"others":true},
  {"title":"Euphoria","year":2019,"others":false},
  {"title":"Feel Good","year":2020,"others":false},
  {"title":"Fingersmith","year":2005,"others":false},
  {"title":"First Kill","year":2022,"others":false},
  {"title":"Fisk","year":2021,"others":true},
  {"title":"Gay Mean Girls","year":2015,"others":false},
  {"title":"Gentleman Jack","year":2019,"others":false},
  {"title":"The Good Fight","year":2017,"others":false},
  {"title":"Grey’s Anatomy","year":2005,"others":false},
  {"title":"Hacks","year":2021,"others":false},
  {"title":"Hal & Harper","year":2025,"others":false},
  {"title":"Harley Quinn","year":2019,"others":false},
  {"title":"The Haunting of Bly Manor","year":2020,"others":false},
  {"title":"The Hunting Wives","year":2025,"others":false},
  {"title":"Interview with the Vampire","year":2022,"others":false},
  {"title":"Jessica Jones","year":2015,"others":false},
  {"title":"The Jetty","year":2024,"others":false},
  {"title":"Killing Eve","year":2018,"others":false},
  {"title":"The L Word","year":2004,"others":false},
  {"title":"The Last of Us","year":2023,"others":false},
  {"title":"The Legend of Korra","year":2012,"others":false},
  {"title":"Leopard Skin","year":2022,"others":false},
  {"title":"LIGGA","year":2021,"others":false},
  {"title":"Lip Service","year":2010,"others":false},
  {"title":"Long Story Short","year":2025,"others":false},
  {"title":"Loving Her","year":2021,"others":false},
  {"title":"Maximum Pleasure Guaranteed","year":2026,"others":true},
  {"title":"Modern Family","year":2009,"others":true},
  {"title":"Monster: The Lizzie Borden Story","year":2026,"others":false},
  {"title":"Orphan Black","year":2013,"others":false},
  {"title":"The Owl House","year":2020,"others":false},
  {"title":"Paper Girls","year":2022,"others":false},
  {"title":"PEN15","year":2019,"others":true},
  {"title":"Person of Interest","year":2011,"others":false},
  {"title":"Piste noire","year":2023,"others":false},
  {"title":"Pluribus","year":2025,"others":false},
  {"title":"Portrait of a Marriage","year":1990,"others":false},
  {"title":"Queer for Fear: The History of Queer Horror","year":2022,"others":false},
  {"title":"Rick and Morty","year":2013,"others":true},
  {"title":"Rizzoli & Isles","year":2010,"others":false},
  {"title":"Señorita 89","year":2022,"others":false},
  {"title":"Severance","year":2022,"others":true},
  {"title":"Sharp Objects","year":2018,"others":false},
  {"title":"She Loves to Cook, and She Loves to Eat","year":2022,"others":false},
  {"title":"She-Hulk: Attorney at Law","year":2022,"others":false},
  {"title":"Silo","year":2023,"others":false},
  {"title":"Sjukt oklar","year":2018,"others":false},
  {"title":"Slow Horses","year":2022,"others":true},
  {"title":"South of Nowhere","year":2005,"others":false},
  {"title":"Special Ops: Lioness","year":2023,"others":false},
  {"title":"Station 19","year":2018,"others":false},
  {"title":"Sterling Point","year":2026,"others":false},
  {"title":"Stranger Things","year":2016,"others":false},
  {"title":"The Studio","year":2025,"others":true},
  {"title":"Succession","year":2018,"others":true},
  {"title":"Supergirl","year":2015,"others":false},
  {"title":"Swimming with Sharks","year":2022,"others":false},
  {"title":"Ted Lasso","year":2020,"others":true},
  {"title":"Teenage Bounty Hunters","year":2020,"others":false},
  {"title":"This Way Up","year":2019,"others":false},
  {"title":"Triple Oh!","year":2024,"others":false},
  {"title":"Twin Peaks","year":1990,"others":true},
  {"title":"Veep","year":2012,"others":true},
  {"title":"Veneno","year":2020,"others":false},
  {"title":"Vigil","year":2021,"others":false},
  {"title":"Warehouse 13","year":2009,"others":false},
  {"title":"Wednesday","year":2022,"others":false},
  {"title":"Wentworth","year":2013,"others":false},
  {"title":"The White Lotus","year":2021,"others":true},
  {"title":"The Wilds","year":2020,"others":false},
  {"title":"WIR","year":2021,"others":false},
  {"title":"Wynonna Earp","year":2016,"others":false},
  {"title":"Yellowjackets","year":2021,"others":false},
  {"title":"Yes, Prime Minister","year":1986,"others":true}
];
